### ISSUE TITLE
Unable to post from Quill using micropub

### ISSUE THREAD

**Issue by davidmead** [idno/known#2326]
## While trying to do this:
Writing a note (tweet) in https://quill.p3k.io/. Entered content, tags, selected to syndicate to Twitter, location, and went to post.  Then it returned an error...

> Something went wrong!
Your Micropub endpoint indicated that something went wrong creating the post.

![image](https://user-images.githubusercontent.com/1266930/51477520-ba35ed00-1d56-11e9-8c4a-532bcdcaa43f.png)

## I encountered this error:
Quill was unable to post and returns this as the micropub response...

```
HTTP/1.1 200 OK
Server: nginx/1.2.1
Date: Mon, 21 Jan 2019 13:19:27 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.0.6
P3P: CP="CAO PSA OUR"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Link: <https://davidjohnmead.com/indieauth/auth>; rel="authorization_endpoint", <https://davidjohnmead.com/indieauth/token>; rel="token_endpoint", <https://davidjohnmead.com/micropub/endpoint>; rel="micropub"
Set-Cookie: known=c9b29972d92bd8efa0d7ffe8d469090aee11713aa2798daa792fde734c3d11c8; expires=Mon, 28-Jan-2019 13:19:27 GMT; Max-Age=604800; path=/; secure; HttpOnly
Vary: User-Agent,Accept-Encoding

<br />
<b>Fatal error</b>:  Uncaught Exception: Access token da3794ef64c480bdde0266c3377287d5 does not match any stored token. in /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php:79
Stack trace:
#0 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php(34): IdnoPlugins\OAuth2\Main::authenticate()
#1 [internal function]: IdnoPlugins\OAuth2\Main-&gt;IdnoPlugins\OAuth2\{closure}(Object(Idno\Core\Event))
#2 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/external/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(Idno\Core\Event))
#3 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/external/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, 'user/auth/reque...', Object(Idno\Core\Event))
#4 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/Idno/Core/Idno.php(348): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch('user/auth/reque...', Obj in <b>/nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php</b> on line <b>79</b><br />
<h1>Oh no! Known experienced a problem!</h1><p>Known experienced a problem with this page and couldn't continue. The technical details are as follows:</p><pre>Fatal Error: /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php:79 - "Uncaught Exception: Access token da3794ef64c480bdde0266c3377287d5 does not match any stored token. in /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php:79
Stack trace:
#0 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/IdnoPlugins/OAuth2/Main.php(34): IdnoPlugins\OAuth2\Main::authenticate()
#1 [internal function]: IdnoPlugins\OAuth2\Main->IdnoPlugins\OAuth2\{closure}(Object(Idno\Core\Event))
#2 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/external/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(Idno\Core\Event))
#3 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/external/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'user/auth/reque...', Object(Idno\Core\Event))
#4 /nfs/c03/h05/mnt/56448/domains/davidjohnmead.com/html/Idno/Core/Idno.php(348): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('user/auth/reque...', Obj", on page davidjohnmead.com/micropub/endpoint</pre><p>If you continue to have problems, <a href="https://withknown.com/opensource" target="_blank">open source users have a number of resources available.</a></p>

```

## Some other notes:
I did pull the latest build from GitHub last week, so everything should be up-to-date.

* Known version = Version 0.9.9-a (2019011501)
* Database = mySQL
* No problem on diagnostic page

**Comment by davidmead** [comment]
Update - Disabling the OAuth2 plugin within Known lets retweets and replies go through from Quill.

**Comment by mapkyca** [comment]
Thanks for that. Looks like there's a fight between oauth2 and micro pub. Probably OAuth not matching shouldn't be an exception, just a failure to authenticate, so other services can attempt.
