### ISSUE TITLE
Dependabot update errors

### ISSUE THREAD

**Issue by lindner** [idno/Known#2869]
## While trying to do this:

Monitor dependabot logs

## I encountered this error:

```
ERROR <job_64511306> Error processing mapkyca/known-mongo-php-library (ArgumentError)
updater | ERROR <job_64511306> Malformed version number string 1.0.3+known
updater | ERROR <job_64511306> /usr/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/version.rb:15:in `initialize'
updater | ERROR <job_64511306> /usr/lib/ruby/2.6.0/rubygems/version.rb:201:in `new'
updater | ERROR <job_64511306> /usr/lib/ruby/2.6.0/rubygems/version.rb:201:in `new'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker/latest_version_finder.rb:82:in `wants_prerelease?'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker/latest_version_finder.rb:55:in `filter_prerelease_versions'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker/latest_version_finder.rb:40:in `fetch_latest_version'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker/latest_version_finder.rb:26:in `latest_version'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker.rb:91:in `latest_version_from_registry'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.130.2/lib/dependabot/composer/update_checker.rb:21:in `latest_version'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:444:in `log_checking_for_update'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:175:in `check_and_create_pull_request'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:66:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_64511306> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:27:in `run'
updater | ERROR <job_64511306> bin/update_files.rb:21:in `<main>'
```

## Some other notes:

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file
* What database are you using? (e.g. mongo, mysql, postgres)
* Any warnings or errors in your admin/diagnostics page?
* If this is a programming bug, can you include examples of any Micropub / API calls / webhook pings you make? Otherwise please don't worry about what this means!
* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by lindner** [comment]
@mapkyca can you take a look at the mongo dep?

**Comment by benwerd** [comment]
I'm taking a look.

**Comment by benwerd** [comment]
Added a PR @mapkyca: https://github.com/mapkyca/known-mongo-php-library/pull/1

**Comment by benwerd** [comment]
Closing as the PR's been merged.
