### ISSUE TITLE
Webmentions throw implode error

### ISSUE THREAD

**Issue by benwerd** [idno/Known#2880]
## While trying to do this:

Send an outgoing webmention

## I encountered this error:

Known raises the following error:

`implode(): Argument #2 ($array) must be of type ?array, string given`, including  the following stack trace:

```
TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /Users/ben/Sites/known/public/vendor/indieweb/mention-client/src/IndieWeb/MentionClient.php:224
Stack trace:
#0 /Users/ben/Sites/known/public/vendor/indieweb/mention-client/src/IndieWeb/MentionClient.php(224): implode(Array, ', ')
#1 /Users/ben/Sites/known/public/vendor/indieweb/mention-client/src/IndieWeb/MentionClient.php(418): IndieWeb\MentionClient->discoverWebmentionEndpoint('http://known.te...')
#2 /Users/ben/Sites/known/public/vendor/indieweb/mention-client/src/IndieWeb/MentionClient.php(400): IndieWeb\MentionClient->sendFirstSupportedMention('http://known.te...', 'http://known.te...')
#3 /Users/ben/Sites/known/public/Idno/Core/Webmention.php(53): IndieWeb\MentionClient->sendMentions('http://known.te...', 'Idno\Core\{closure}(Object(Idno\Core\Event), 'webmention/send...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 /Users/ben/Sites/known/public/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'webmention/send...', Object(Idno\Core\Event))
#7 /Users/ben/Sites/known/public/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'webmention/send...', Object(Idno\Core\Event))
#8 /Users/ben/Sites/known/public/Idno/Core/EventDispatcher.php(61): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Idno\Core\Event), Object(Idno\Core\Event))
#9 /Users/ben/Sites/known/public/Idno/Core/SynchronousQueue.php(14): Idno\Core\EventDispatcher->triggerEvent('webmention/send...', Array)
#10 /Users/ben/Sites/known/public/IdnoPlugins/Status/Status.php(127): Idno\Core\SynchronousQueue->enqueue('default', 'webmention/send...', Array)
#11 /Users/ben/Sites/known/public/IdnoPlugins/Status/Pages/Edit.php(61): IdnoPlugins\Status\Status->saveDataFromInput()
#12 /Users/ben/Sites/known/public/Idno/Common/Page.php(392): IdnoPlugins\Status\Pages\Edit->postContent()
#13 /Users/ben/Sites/known/public/vendor/idno/torophp/src/Toro.php(69): Idno\Common\Page->post()
#14 /Users/ben/Sites/known/public/index.php(60): Toro::serve(Object(Idno\Core\PageHandler))
#15 {main}      
```

This seems fairly straightforward, although I'm confused about why it's arising now. I'm on the case.

**Comment by benwerd** [comment]
This turned out to be an upstream error in the indieweb mention client. I submitted a PR over here: https://github.com/indieweb/mention-client-php/pull/39

I'll leave this issue open until the code there is merged.

**Comment by benwerd** [comment]
Fixed upstream.
