### ISSUE TITLE
Crash while editing a post

### ISSUE THREAD

**Issue by pierreozoux** [idno/Known#740]
The specific action was inserting link, save, and then the content is not editable anymore... 

Here is the stacktrace for reference.

```
"DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/Promise-backend.js", line 870, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 684, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://translator-at-dontfollowme-dot-net/translator/lib/main.js", line 1, in null
    var widgets = require('widget')
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 591, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);" deprecate.js:21
Error: The page is currently hidden and can no longer be used until it is visible again.
Stack trace:
send@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/pierre/.mozilla/firefox/r3g3ulro.dev-edition-default/extensions/jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-parent.js:94:1
load/pageModGoogle<.onAttach/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/pierre/.mozilla/firefox/r3g3ulro.dev-edition-default/extensions/jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-zadieub7xozojw-at-jetpack/ddg_for_firefox/lib/ddg-pagemods.js:58:1
emit@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/pierre/.mozilla/firefox/r3g3ulro.dev-edition-default/extensions/jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:97:9
receive@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/pierre/.mozilla/firefox/r3g3ulro.dev-edition-default/extensions/jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-parent.js:81:26
 core.js:91
"The creation of property views was cancelled because the computed-view was destroyed before it was done creating views" computed-view.js:594
"Could not set the unique selector for the newly selected node, the inspector was destroyed." inspector-panel.js:441
"markup view destroyed" deprecated-sync-thenables.js:48
"Could not show the node, the markup-view was destroyed while waiting for children" markup-view.js:781
"Could not mark node as selected, the markup-view was destroyed while showing the node." markup-view.js:379
"markup view destroyed" deprecated-sync-thenables.js:48
"Nothing to show." core.js:91
"Could not set the unique selector for the newly selected node, the inspector was destroyed." inspector-panel.js:441
"markup view destroyed" deprecated-sync-thenables.js:48
"Could not show the node, the markup-view was destroyed while waiting for children" markup-view.js:781
"Could not mark node as selected, the markup-view was destroyed while showing the node." markup-view.js:379
"markup view destroyed" deprecated-sync-thenables.js:48
TypeError: self.selection is null
Stack trace:
InspectorPanel.prototype.updating/this._updateProgress.checkDone@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/inspector/inspector-panel.js:478:1
InspectorPanel.prototype.updating/done@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/inspector/inspector-panel.js:495:7
InspectorPanel_onNewSelection/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/inspector/inspector-panel.js:450:9
 inspector-panel.js:452
"Could not set the unique selector for the newly selected node, the inspector was destroyed." inspector-panel.js:441
"Nothing to show." core.js:91
TypeError: can't access dead object
Stack trace:
WalkerActor<.querySelector<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/inspector.js:1727:9
actorProto/</handler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/protocol.js:1004:19
DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1422:15
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:545:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
 protocol.js:898
"Protocol error (unknownError): TypeError: can't access dead object" protocol.js:18
"Protocol error (unknownError): TypeError: can't access dead object" Promise-backend.js:873
"Nothing to show." core.js:91
"[cycle] terminating; zero elements found by selector" jquery.cycle.all.js:35:2
"JQMIGRATE: Logging is active" jquery-migrate-1.1.1.js:21:1
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:62889
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:63396
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:63907
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:64422
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:64919
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:65649
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:66304
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:66788
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:67140
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:67802
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:68259
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:68611
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:69285
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:71009
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:71219
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:72248
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:73581
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:73734
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:74243
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:75052
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:75243
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:76272
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:77611
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:77796
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:78305
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:79120
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:79316
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:79825
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:80650
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:81372
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:81481
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:82620
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:84105
Error in parsing value for 'background-image'.  Declaration dropped. load.php:1:84904
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:86027
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:87034
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. load.php:1:87492
Error in parsing value for 'unicode-bidi'.  Declaration dropped. Webmention:2:139
Error in parsing value for 'unicode-bidi'.  Declaration dropped. Webmention:2:168
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:2:4451
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:6:609
Unknown property 'user-select'.  Declaration dropped. Webmention:4:347
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:6:1878
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. Webmention:6:2104
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. Webmention:6:2196
Unknown property 'user-select'.  Declaration dropped. Webmention:8:114
Unknown property '-moz-box-shadow'.  Declaration dropped. Webmention:12:306
Unknown property '-moz-box-shadow'.  Declaration dropped. Webmention:12:538
Unknown property '-moz-box-shadow'.  Declaration dropped. Webmention:12:969
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. Webmention:12:1807
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. Webmention:12:1860
Error in parsing value for 'background-image'.  Declaration dropped. Webmention:16:894
Error in parsing value for 'background-image'.  Declaration dropped. Webmention:16:1290
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:16:2020
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:18:1128
Error in parsing value for 'background-image'.  Declaration dropped. Webmention:18:1148
Error in parsing value for 'background-image'.  Declaration dropped. Webmention:18:2752
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:18:4738
Dangling combinator.  Ruleset ignored due to bad selector. Webmention:4:380
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:4:3399
Expected 'important' but found 'ie'.  Expected ';' or '}' to terminate declaration but found 'ie'.  Declaration dropped. Webmention:4:5991
Expected end of selector or a user action pseudo-class after pseudo-element but found ':'.  Ruleset ignored due to bad selector. Webmention:4:6069
TypeError: gBrowser.contentWindow is undefined overlay.js:431:0
Unknown property 'zoom'.  Declaration dropped. commonPrint.css:245:5
Expected declaration but found '*'.  Skipped to next declaration. commonPrint.css:246:1
Unknown property 'speak'.  Declaration dropped. handheld.css:464:6
Unknown property '-moz-border-radius'.  Declaration dropped. handheld.css:1264:21
Unknown property 'speak'.  Declaration dropped. main.css:505:6
Unknown property '-moz-border-radius'.  Declaration dropped. main.css:1559:21
Error in parsing value for 'white-space'.  Declaration dropped. gumax_template.css:598:21
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. gumax_template.css:891:34
Unknown property '-moz-border-radius-topright'.  Declaration dropped. gumax_template.css:892:35
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. gumax_template.css:893:37
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. gumax_template.css:894:38
Unknown property '-moz-border-radius'.  Declaration dropped. gumax_cyborg.css:189:19
ReferenceError: stylepath is not defined wikibits.js:586:0
ReferenceError: jQuery is not defined dots.js:78:0
ReferenceError: $ is not defined webmention:50:2
Unknown property '-moz-border-radius'.  Declaration dropped. webmention:1050:19
TypeError: gBrowser.contentWindow is undefined overlay.js:40:0
TypeError: f is null Raphael.js:7:14873
Empty string passed to getElementById(). jquery.min.js:2:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. webmention
TypeError: gBrowser.contentWindow is undefined overlay.js:431:0
ReferenceError: stylepath is not defined wikibits.js:586:0
ReferenceError: jQuery is not defined dots.js:78:0
ReferenceError: $ is not defined Special:Search:48:2
Unknown property '-moz-border-radius'.  Declaration dropped. Special:Search:368:19
TypeError: gBrowser.contentWindow is undefined overlay.js:40:0
TypeError: f is null Raphael.js:7:14873
TypeError: gBrowser.contentWindow is undefined overlay.js:431:0
ReferenceError: stylepath is not defined wikibits.js:586:0
ReferenceError: jQuery is not defined dots.js:78:0
ReferenceError: $ is not defined pingback:49:2
Unknown property '-moz-border-radius'.  Declaration dropped. pingback:435:19
TypeError: gBrowser.contentWindow is undefined overlay.js:40:0
TypeError: f is null Raphael.js:7:14873
Empty string passed to getElementById(). jquery.min.js:2:0
"Could not set the unique selector for the newly selected node, the inspector was destroyed." inspector-panel.js:441

```

**Comment by benwerd** [comment]
Uh oh. To clarify, is this on the very latest code (which uses TinyMCE) or the latest stable (which uses Summernote)?

**Comment by pierreozoux** [comment]
I'm still on the last stable. Then let's close it :)
